<?php

namespace Database\Seeders;

use App\Models\RequestingDoctor;
use Illuminate\Database\Seeder;

class RequestingDoctorsSeeder extends Seeder
{
    public function run(): void
    {
        $names = [
            'ABEL CALLOAPAZA PARI',
            'ALCIDES CARREON QUISPE',
            'ALEJANDRA ONTON MORALES',
            'ALFONSO LAZO ROJAS',
            'JOSE A. SAIRITUPA FLORES',
            'ALFREDO TUMI FIGUEROA',
            'ALIPIO CONDORI HUAYHUA',
            'ALONSO RICARDO ZENTENO ARCE',
            'AMPARO TITO CHIRIBOGA',
            'ANDRE MARCEL MOLINA ARIAS',
            'ANDREE R. YERBA COANQUI',
            'ANDRES MIGUEL CACERES JARA',
            'ANGEL VILCA QUISPE',
            'ANGELA ALMENDRA CARPIO INQUILLA',
            'ARTURO VALENCIA TORRES',
            'WALTER TITO CASTELLANO',
            'BLANCA LLERENA VILLAFUERTE',
            'BRAYAN MENDOZA VILLEGAS',
            'BREDY HERRERA GARCIA',
            'MARCO RETAMOZO',
            'BRYAM ROJAS ORTIZ',
            'CARLOS ANGEL LOAYZA COILA',
            'CARLOS CAMPOS COBEÑA',
            'CATHERINE RUIZ PEREA',
            'CESAR A. LLERENA ZEA',
            'CESAR ADOLFO CHAYÑA CHAYÑA',
            'CHRISTIAN PENADILLO TREYEJO',
            'CLINICA SAUCES',
            'JUAN CARLOS TALAVERA ROJAS',
            'DANIEL AMARO MEDRANO',
            'DANIELA A. AMARO MEDRANO',
            'DEMHOS ACHAHUANCO APAZA',
            'EDER L. SAYRITUPA FLORES',
            'ANGELA GABRIELA BEDOYA TAPIA',
            'EDISON OCHOA MERMA',
            'EDITH CERPA PAREDES',
            'JUAN NICOLAS HUALLAPUMA LIMA',
            'EDUARDO EDWIN APAZA ECHEGARAY',
            'EDWIN ZEVALLOS VALDIVIA',
            'EDWIN LUQUE CHAIÑA',
            'EDWIN P. MACHACA YUJRA',
            'EDWIN ZEVILLANOS SANCHEZ',
            'ELVA CATHERINE QUELOPANA VILLARROEL',
            'ENMA JARA CALLOHUANCA',
            'ENRIQUE VARGAS SIHUINTA',
            'EVA NEISSON HOLGUIN HUMPIRE',
            'EVERT ANTONIO TITO MAMANI',
            'EYNER E. CHOQUE ZELA',
            'F. DANIEL CURI TITO',
            'FELIX GOMEZ APAZA',
            'FELIX POMA CACHICATARI',
            'FRANCO P. LLERENA ZEA',
            'FRANCO PINEDA ALEX',
            'FREDY MEDINA SANTILLANA',
            'GABRIEL E. MAMANI SUCASAIRE',
            'LEYDI CACERES ARROYO',
            'GERSON SALAZAR VALDEZ',
            'GIULIANA Y. BEROLATI OBANDO',
            'GONZALO ARPASI CHAHUARES',
            'GUSTAVO AROHUANCA PERCCA',
            'HANS HUMPIRI NUÑEZ',
            'HAYDEE BARRIOS MONTEAGUDO',
            'HECTOR M. CANEPA V.',
            'HIDALGO GONGORA ALFREDO A.',
            'HUAMAN FARFAN HECTOR',
            'ILLACUTIPA MAMANI ABAD',
            'INQUILLA CASTILLO HUBERT J.',
            'IVAN DANTE VARGAS NINA',
            'IVNER E. CHOQUE ZELA',
            'JAIR VALDO VILCA VALENZUELA',
            'JAVIER L. ALARCON ROJAS',
            'JEFREE FERNANDEZ CHAVEZ',
            'JESUS A CACERES DIAZ',
            'JESUS E. LLERENA ZEA',
            'JHON UVER MACHACA MONROY',
            'JONAS LLAVILLA QUISPE',
            'JORGE W. EYZAGUIRRE DELGADO',
            'JORGE YSAAC LOPEZ TEJADA',
            'JOSE A. RUELAS LLERENA',
            'JOSÉ ALEXANDER SAYRITUPA FLORES',
            'JOSE LEON CHIRINOS REVILLA',
            'JOSEPH R. PORTILLO CAZORLA',
            'JOSEPH BRIAN HUENECE SARANIBAR',
            'JUAN CARLOS RAMOS MAMANI',
            'JUAN CARLOS ROJAS',
            'JUAN CARLOS VARGAS NINA',
            'JUAN MANUEL ARAGON VELARDE',
            'JULIAN CUNO ONQUE',
            'JULIO CESAR FLORES PORTUGAL',
            'KARELA DIAZ RODRIGUEZ',
            'KATIA LUZ CONDORENA',
            'KENDO CHOQUEHUANCA FUENTES',
            'LAURA MAMANI EDUARDO',
            'LEONIDAS PACOMPIA PARISUAÑA',
            'LEOPOLDO TUNI VALDIVIA',
            'MARCO TITO CARCASI',
            'LIZBETH R. OCHOCHOQUE BORDA',
            'LUIS AMADOR MACHACA PAREDES',
            'LUIS ANGEL APAZA HUARACHI',
            'LUIS ANTONIO MALDONADO NEYRA',
            'LUIS FERNANDO HERRERA OPORTO',
            'LUZ CONDORENA PINO',
            'MANUEL CARRION DONGO',
            'MARCO A. LLANQUI LLANQUE',
            'MARCO A. MAMANI GAMARRA',
            'MARCO ANTONIO QUISPE CHOQUECHAMBI',
            'GUSTAVO SALCEDO MOLINA',
            'MARIA CRISTINA TORRES',
            'MARILYN A. AGUILAR GOYZUETA',
            'MARINA FERNANDEZ TITO',
            'MARIO ORIHUELA GUTIERREZ',
            'MARTIN ALVARO ORDOÑEZ',
            'MIDWAR H. ARELA YACASI',
            'MIGUEL ANGEL APAZA MAQUERA',
            'MILAGROS E. ARIZACA ASCARRUZ',
            'MILAGROS ORDOÑEZ RODRIGUEZ',
            'MILAN HUARACALLO TACURI',
            'MILDRED PILCO AVARCA',
            'MILTON ANCO AGUILAR',
            'MILTON CHAVEZ LUPACA',
            'MIRANDA MARTINEZ ESTEFANY E.',
            'LIZ CACERES',
            'MONTENEGRO SANTA CRUZ',
            'NATALI ABAD ILLACUTIPA MAMANI',
            'NEPTALI PILCO GONZALES',
            'NILTON A. CRUZ TICONA',
            'NOE CABRERA OBLITAS',
            'NOEMI AMPARO PINAZO RAMOS',
            'OCTAVIO E. ARIAS CANAZA',
            'ODDY VANEGAS CHAMBILLA',
            'OLIVER CHEVARRIA C',
            'OLIVER M. GUTIERRERZ TRIVEÑO',
            'OSCAR JOSUE RIOS ZEA',
            'CARLOS ANIBAL COACALLA RUELAS',
            'PAUL FLORES YUCRA',
            'ANA BEDOYA CARDENAS',
            'PERCY EDUARDO MESTAS FLORES',
            'POMA CACHICATARI FELIX EDUARDO',
            'PRISCILA R. DIAZ CASTILLO',
            'RAUL TICONA TILA',
            'RENDO R. LOZA PEÑA',
            'RICARDO ROCA TORRES',
            'RIGOBERTO CUTIMBO LUQUE',
            'ROBERTO MAYTA JARA',
            'ROGER F. SANCHEZ VALDEZ',
            'ROMULO PARI PARI',
            'ROMY PARI TORRES',
            'RONALD HURTADO DELGADO',
            'RONALD ROLDAN CAMARA',
            'RONALDO ROJAS APAZA',
            'ROSMERY LAURA ESPEJO',
            'ROY HUAYHUA BLANCO',
            'CARLOS CHURATA RAMOS',
            'SAUL MARCOS HUAQUISTO CHOQUE',
            'SHUELI SUMAYA APAZA AGUILAR',
            'SOLEDAD GONZALES GONZALES',
            'SOTOMAYOR ABARCA EDUARDO',
            'STALIN LUPACA CHARCA',
            'SUSANA GUEVURA YANQUI',
            'TANIA AGUILAR PORTUGAL',
            'TEODORO BUTRON CARDENAS',
            'TORRES BASURCO ALFREDO',
            'VALERIA X. MOLLEAPAZA MIRANDA',
            'VANESSA SANCHEZ NINA',
            'VICTOR ISMAEL LAZO GAMERO',
            'VICTOR JAVIER PERCCA MARCA',
            'VIDMAR MENGOA HERRERA',
            'JOSUE CONDORI LUQUE',
            'WALKER APAZA CANAZA',
            'WILBER S. TICONA ARAPA',
            'WILBERT CALCINA HUAYTA',
            'WILLIAM ELVIS LOPEZ ARTEAGA',
            'WILLIAMS TAGLE CAÑAPATAÑA',
            'WILLY H. AMANQUI RUELAS',
            'WILSON MUJICA SOLOGUREN',
            'YATSEN CHIARA COILA',
            'YENY LUVE JALIRI',
            'YESSIKA GOMEZ PEÑALOZA',
            'YULI GIOVANNA BERNEDO LAURA',
            'YUMI B. MENDOZA CASA',
            'YURIELA Y. SALAZAR SANIZO',
            'DAVID MORENO',
        ];

        foreach ($names as $name) {
            RequestingDoctor::updateOrCreate(
                ['nombre' => $name],
                ['activo' => true]
            );
        }
    }
}
