<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
    @php
        $money = fn ($value) => number_format((float) $value, 2, '.', '');
        $text = fn ($value) => htmlspecialchars((string) $value, ENT_QUOTES | ENT_XML1, 'UTF-8');
    @endphp
    <Styles>
        <Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Center" ss:WrapText="1"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/></Borders><Font ss:FontName="Calibri" ss:Size="10" ss:Color="#1E293B"/></Style>
        <Style ss:ID="Title"><Font ss:FontName="Calibri" ss:Size="16" ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#0F766E" ss:Pattern="Solid"/></Style>
        <Style ss:ID="Header"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Font ss:FontName="Calibri" ss:Size="10" ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#0F766E" ss:Pattern="Solid"/></Style>
        <Style ss:ID="Money"><NumberFormat ss:Format="&quot;S/ &quot;#,##0.00"/></Style>
        <Style ss:ID="Integer"><Alignment ss:Horizontal="Center"/><NumberFormat ss:Format="0.00"/></Style>
        <Style ss:ID="Total"><Font ss:Bold="1"/><Interior ss:Color="#FEF3C7" ss:Pattern="Solid"/></Style>
    </Styles>
    @foreach($dailyClosings as $closing)
        <Worksheet ss:Name="{{ $closing['date']->format('d-m-Y') }}">
            <Table>
                <Column ss:Width="35"/><Column ss:Width="70"/><Column ss:Width="150"/><Column ss:Width="75"/><Column ss:Width="100"/><Column ss:Width="110"/><Column ss:Width="110"/><Column ss:Width="170"/><Column ss:Width="70"/><Column ss:Width="75"/><Column ss:Width="125"/><Column ss:Width="75" ss:Span="6"/><Column ss:Width="130"/><Column ss:Width="140"/><Column ss:Width="130"/><Column ss:Width="85"/>
                <Row ss:Height="30"><Cell ss:StyleID="Title" ss:MergeAcross="21"><Data ss:Type="String">CUADRE DIARIO - {{ $closing['date']->format('d/m/Y') }}</Data></Cell></Row>
                <Row ss:Height="32"><Cell ss:StyleID="Header"><Data ss:Type="String">N°</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Fecha</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Paciente</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">DNI</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Orden de servicio</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Tipo de comprobante</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">N° comprobante</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Tipo de tomografía</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">S/C C/C</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Uso Iopamidol</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Convenio</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Total cobrado</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Yape</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Transferencia</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Por cobrar</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Placas utilizadas</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Saldo placas</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Saldo Iopamidol</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Médico solicitante</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Doctor informe</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Gasto</Data></Cell><Cell ss:StyleID="Header"><Data ss:Type="String">Monto gasto</Data></Cell></Row>
                @php $plateRunning = $closing['plateSummary']['initial']; $iopamidolRunning = $closing['iopamidolSummary']['initial']; $maxRows = max($closing['orders']->count(), $closing['expenses']->count()); @endphp
                @for($i = 0; $i < $maxRows; $i++)
                    @php
                        $order = $closing['orders']->get($i); $expense = $closing['expenses']->get($i);
                        $plates = $order ? (float) (($order->admissionForm?->data['delivery_quantities']['PLACAS'] ?? $order->admissionForm?->data['plates_count'] ?? 0)) : 0;
                        $iopamidol = $order ? (float) $order->consumables->filter(fn ($item) => str_contains(strtolower($item->reagent->nombre ?? ''), 'iopamidol'))->sum('cantidad') : 0;
                        $plateRunning -= $plates; $iopamidolRunning -= $iopamidol;
                    @endphp
                    <Row><Cell><Data ss:Type="Number">{{ $i + 1 }}</Data></Cell><Cell><Data ss:Type="String">{{ $order?->fecha_orden?->format('d/m/Y') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order ? trim(($order->patient->nombres ?? '').' '.($order->patient->apellidos ?? '')) : '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->patient->dni ?? '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->codigo_orden ?? '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->tipo_comprobante ?? '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->numero_comprobante ?? '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order?->orderExams?->pluck('exam.nombre_examen')->filter()->join(' + ')) }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order?->orderExams?->pluck('tipo_contraste')->filter()->join(', ')) }}</Data></Cell><Cell ss:StyleID="Integer"><Data ss:Type="Number">{{ $iopamidol }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->agreement->nombre_institucion ?? '') }}</Data></Cell><Cell ss:StyleID="Money"><Data ss:Type="Number">{{ $order ? $money($order->total) : 0 }}</Data></Cell><Cell ss:StyleID="Money"><Data ss:Type="Number">{{ $order?->tipo_pago === 'Yape/Plin' ? $money($order->total) : 0 }}</Data></Cell><Cell ss:StyleID="Money"><Data ss:Type="Number">{{ $order?->tipo_pago === 'Transferencia' ? $money($order->total) : 0 }}</Data></Cell><Cell ss:StyleID="Money"><Data ss:Type="Number">{{ $order?->tipo_pago === 'Convenio' ? $money($order->total) : 0 }}</Data></Cell><Cell ss:StyleID="Integer"><Data ss:Type="Number">{{ $plates }}</Data></Cell><Cell ss:StyleID="Integer"><Data ss:Type="Number">{{ $order ? $plateRunning : 0 }}</Data></Cell><Cell ss:StyleID="Integer"><Data ss:Type="Number">{{ $order ? $iopamidolRunning : 0 }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->medicoSolicitante->nombre ?? '') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($order->medicoInforme->nombre_completo ?? 'SIN INFORME') }}</Data></Cell><Cell><Data ss:Type="String">{{ $text($expense->descripcion ?? '') }}</Data></Cell><Cell ss:StyleID="Money"><Data ss:Type="Number">{{ $expense ? $money($expense->monto) : 0 }}</Data></Cell></Row>
                @endfor
                <Row><Cell ss:StyleID="Total" ss:MergeAcross="8"><Data ss:Type="String">TOTALES DEL DÍA</Data></Cell><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $closing['iopamidolSummary']['delivered'] }}</Data></Cell><Cell ss:StyleID="Total"/><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $money($closing['incomeTotal']) }}</Data></Cell><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $money($closing['yapePlinIncome']) }}</Data></Cell><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $money($closing['transferIncome']) }}</Data></Cell><Cell ss:StyleID="Total"/><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $closing['plateSummary']['delivered'] }}</Data></Cell><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $closing['plateSummary']['final'] }}</Data></Cell><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $closing['iopamidolSummary']['final'] }}</Data></Cell><Cell ss:StyleID="Total" ss:MergeAcross="1"><Data ss:Type="String">TOTAL GASTOS</Data></Cell><Cell ss:StyleID="Total"/><Cell ss:StyleID="Total"><Data ss:Type="Number">{{ $money($closing['expenseTotal']) }}</Data></Cell></Row>
            </Table>
        </Worksheet>
    @endforeach
</Workbook>
