@extends('layouts.app')
@section('content')
<div class="container">
 <section class="clinic-page-hero mb-4"><div class="d-flex justify-content-between align-items-center gap-3"><div><div class="clinic-eyebrow mb-2">Catálogo operativo</div><h1 class="display-6 fw-bold mb-2">Convenios</h1><p class="mb-0 opacity-75">Administra este módulo con edición rápida en modal.</p></div><button class="btn btn-clinic-primary px-4 py-3" data-bs-toggle="modal" data-bs-target="#createModal">+ Nuevo</button></div></section>
 <div class="card clinic-card"><div class="card-header clinic-toolbar p-3"><form method="GET"><div class="clinic-search"><span class="clinic-search-icon">⌕</span><input class="form-control" name="search" value="{{ $search }}" placeholder="Buscar..."></div></form></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0 table-clinic"><thead><tr><th>Institución</th><th>Estado</th><th>Precios</th><th>Órdenes</th><th class="text-end">Acciones</th></tr></thead><tbody>@forelse($agreements as $item)<tr><td class="fw-bold">{{ $item->nombre_institucion }}</td><td><span class="badge {{ $item->activo?'badge-active':'badge-inactive' }}">{{ $item->activo?'Activo':'Inactivo' }}</span></td><td>{{ $item->prices_count }}</td><td>{{ $item->orders_count }}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#edit{{ $item->id }}">Editar</button><button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#del{{ $item->id }}">Eliminar</button></td></tr>@empty<tr><td colspan="5" class="text-center py-5">Sin registros.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer bg-white border-0">{{ $agreements->links() }}</div></div>
</div>
@include('agreements.modal',['id'=>'createModal','title'=>'Crear convenio','action'=>route('agreements.store'),'method'=>'POST','item'=>null])
@foreach($agreements as $item) @include('agreements.modal',['id'=>'edit'.$item->id,'title'=>'Editar convenio','action'=>route('agreements.update',$item),'method'=>'PUT','item'=>$item]) @include('shared.delete',['id'=>'del'.$item->id,'action'=>route('agreements.destroy',$item),'name'=>$item->nombre_institucion]) @endforeach
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script>document.addEventListener('DOMContentLoaded',()=>{@if(session('success'))Swal.fire({icon:'success',title:'Listo',text:@json(session('success')),timer:2200,showConfirmButton:false});@endif @if(session('error'))Swal.fire({icon:'error',title:'Atención',text:@json(session('error'))});@endif @if($errors->any())Swal.fire({icon:'error',title:'Revisa el formulario',text:'Hay campos pendientes o inválidos.'});@endif});</script>@endpush
