<Worksheet ss:Name="{{ $sheetName }}">
    <Table>
        <Column ss:AutoFitWidth="1" ss:Width="105"/><Column ss:AutoFitWidth="1" ss:Width="95"/><Column ss:AutoFitWidth="1" ss:Width="170"/><Column ss:AutoFitWidth="1" ss:Width="145"/><Column ss:AutoFitWidth="1" ss:Width="90"/><Column ss:AutoFitWidth="1" ss:Width="120"/><Column ss:AutoFitWidth="1" ss:Width="110"/><Column ss:AutoFitWidth="1" ss:Width="90"/><Column ss:AutoFitWidth="1" ss:Width="105"/><Column ss:AutoFitWidth="1" ss:Width="80"/>
        <Row><Cell><Data ss:Type="String">Fecha</Data></Cell><Cell><Data ss:Type="String">Orden</Data></Cell><Cell><Data ss:Type="String">Paciente</Data></Cell><Cell><Data ss:Type="String">Convenio</Data></Cell><Cell><Data ss:Type="String">Pago</Data></Cell><Cell><Data ss:Type="String">Tipo de comprobante</Data></Cell><Cell><Data ss:Type="String">N° comprobante</Data></Cell><Cell><Data ss:Type="String">Placas usadas</Data></Cell><Cell><Data ss:Type="String">Iopamidol usado</Data></Cell><Cell><Data ss:Type="String">Total</Data></Cell></Row>
        @foreach($sheetOrders as $order)
            @php $platesUsed = (float) ($order->admissionForm?->data['delivery_quantities']['PLACAS'] ?? $order->admissionForm?->data['plates_count'] ?? 0); $iopamidolUsed = (float) $order->consumables->filter(fn ($item) => str_contains(strtolower($item->reagent->nombre ?? ''), 'iopamidol'))->sum('cantidad'); @endphp
            <Row><Cell><Data ss:Type="String">{{ $order->fecha_orden->format('d/m/Y H:i') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars($order->codigo_orden ?? '#'.$order->id, ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars(($order->patient->nombres ?? '').' '.($order->patient->apellidos ?? ''), ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars($order->agreement->nombre_institucion ?? '—', ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars($order->tipo_pago ?? '—', ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars($order->tipo_comprobante ?? '—', ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="String">{{ htmlspecialchars($order->numero_comprobante ?? '—', ENT_QUOTES | ENT_XML1, 'UTF-8') }}</Data></Cell><Cell><Data ss:Type="Number">{{ $platesUsed }}</Data></Cell><Cell><Data ss:Type="Number">{{ $iopamidolUsed }}</Data></Cell><Cell><Data ss:Type="Number">{{ number_format((float) $order->total, 2, '.', '') }}</Data></Cell></Row>
        @endforeach
    </Table>
</Worksheet>
