<?php
namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\Reagent;
use App\Models\StockMovement;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class StockMovementController extends Controller{
 public function index(Request $request):View{ $search=trim((string)$request->query('search')); $report=$this->reportData($request); $movements=StockMovement::with(['reagent','order','user'])->when($search!=='',fn($q)=>$q->where('motivo','like',"%{$search}%")->orWhereHas('reagent',fn($qq)=>$qq->where('nombre','like',"%{$search}%")))->latest('fecha_movimiento')->paginate(10)->withQueryString(); $reagents=Reagent::where('activo',true)->orderBy('nombre')->get(); $orders=Order::latest()->limit(50)->get(); return view('stock-movements.index',compact('movements','reagents','orders','search','report'));}
 public function downloadReport(Request $request):StreamedResponse{ $report=$this->reportData($request); $filename='reporte-movimientos-stock-'.$report['period'].'-'.$report['from']->format('Y-m-d').'-'.$report['to']->format('Y-m-d').'.csv'; return response()->streamDownload(function()use($report){ $out=fopen('php://output','w'); fputcsv($out,['Reporte de movimientos de consumibles / reactivos']); fputcsv($out,['Periodo',$report['label']]); fputcsv($out,['Desde',$report['from']->format('d/m/Y H:i')]); fputcsv($out,['Hasta',$report['to']->format('d/m/Y H:i')]); fputcsv($out,[]); fputcsv($out,['Reactivo','Unidad','Stock registrado','Ingresos','Salidas','Ajustes','Balance del periodo','Movimientos']); foreach($report['summary'] as $row){ fputcsv($out,[$row['reagent']->nombre,$row['reagent']->unidad,$row['reagent']->stock_actual,$row['Ingreso'],$row['Salida'],$row['Ajuste'],$row['balance'],$row['movements_count']]); } fputcsv($out,[]); fputcsv($out,['Detalle de movimientos']); fputcsv($out,['Fecha','Reactivo','Tipo','Cantidad','Unidad','Motivo','Orden','Usuario','Stock registrado']); foreach($report['movements'] as $movement){ fputcsv($out,[$movement->fecha_movimiento->format('d/m/Y H:i'),$movement->reagent?->nombre,$movement->tipo_movimiento,$movement->cantidad,$movement->reagent?->unidad,$movement->motivo,$movement->order?->codigo_orden ?? $movement->order_id,$movement->user?->nombre_completo ?? $movement->user?->username,$movement->reagent?->stock_actual]); } fclose($out); },$filename,['Content-Type'=>'text/csv; charset=UTF-8']);}
 public function store(Request $request):RedirectResponse{ $data=$this->validatedData($request); $data['user_id']=auth()->id(); DB::transaction(function()use($data){ $movement=StockMovement::create($data); $this->applyStock($movement); }); return redirect()->route('stock-movements.index')->with('success','Movimiento registrado correctamente.');}
 public function destroy(StockMovement $stockMovement):RedirectResponse{ DB::transaction(function()use($stockMovement){ $this->reverseStock($stockMovement); $stockMovement->delete(); }); return redirect()->route('stock-movements.index')->with('success','Movimiento eliminado y stock revertido.');}
 private function validatedData(Request $request):array{return $request->validate(['reagent_id'=>['required','exists:reagents,id'],'tipo_movimiento'=>['required',Rule::in(['Ingreso','Salida','Ajuste'])],'cantidad'=>['required','numeric','min:0.01'],'motivo'=>['nullable','string','max:255'],'order_id'=>['nullable','exists:orders,id'],'fecha_movimiento'=>['required','date']]);}
 private function reportData(Request $request):array{ $period=$request->query('period','daily'); $date=Carbon::parse($request->query('date',now()->toDateString())); [$from,$to,$label]=match($period){ 'weekly'=>[$date->copy()->startOfWeek(),$date->copy()->endOfWeek(),'Semanal'], 'biweekly'=>[$date->copy()->day<=15?$date->copy()->startOfMonth():$date->copy()->day(16)->startOfDay(),$date->copy()->day<=15?$date->copy()->day(15)->endOfDay():$date->copy()->endOfMonth(),'Quincenal'], 'monthly'=>[$date->copy()->startOfMonth(),$date->copy()->endOfMonth(),'Mensual'], default=>[$date->copy()->startOfDay(),$date->copy()->endOfDay(),'Diario'], }; $period=in_array($period,['daily','weekly','biweekly','monthly'],true)?$period:'daily'; $movements=StockMovement::with(['reagent','order','user'])->whereBetween('fecha_movimiento',[$from,$to])->orderBy('fecha_movimiento')->get(); $summary=Reagent::orderBy('nombre')->get()->map(function($reagent)use($movements){ $items=$movements->where('reagent_id',$reagent->id); $ingreso=(float)$items->where('tipo_movimiento','Ingreso')->sum('cantidad'); $salida=(float)$items->where('tipo_movimiento','Salida')->sum('cantidad'); $ajuste=(float)$items->where('tipo_movimiento','Ajuste')->sum('cantidad'); return ['reagent'=>$reagent,'Ingreso'=>$ingreso,'Salida'=>$salida,'Ajuste'=>$ajuste,'balance'=>$ingreso+$ajuste-$salida,'movements_count'=>$items->count()]; }); return compact('period','from','to','label','movements','summary');}
 private function applyStock(StockMovement $m):void{ $r=$m->reagent()->lockForUpdate()->first(); $r->stock_actual = $m->tipo_movimiento==='Salida' ? $r->stock_actual-$m->cantidad : $r->stock_actual+$m->cantidad; $r->save();}
 private function reverseStock(StockMovement $m):void{ $r=$m->reagent()->lockForUpdate()->first(); $r->stock_actual = $m->tipo_movimiento==='Salida' ? $r->stock_actual+$m->cantidad : $r->stock_actual-$m->cantidad; $r->save();}
}
